name: "Backend PR Lint (Python)"

on:
  pull_request:
    branches: [ main ]    # main 브랜치로 merge되기 전 PR에 대해서만

jobs:
  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # working-directory: ./backend   # 만약 requirements.txt가 backend/에 있을 때

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        # working-directory: ./backend

      - name: Run Python tests
        run: |
          pip install pytest
          pytest
        # working-directory: ./backend
