# .github/workflows/lint-on-pr.yml
name: "PR Lint Check"

# PR이 생성되거나 업데이트될 때마다 실행
on:
  pull_request:
    branches: ["answer"]
    types: [opened, synchronize, reopened]

jobs:
  lint-backend:
    name: Backend Lint
    runs-on: ubuntu-latest
    working-directory: ./ # 만약 monorepo라면 backend 서브폴더 지정
    steps:
      - name: GitHub 레포지토리의 코드 체크아웃
        uses: actions/checkout@v3

      - name: Python 설정 (버전 지정)
        uses: actions/setup-python
        with:
          python-version: "3.12" # 프로젝트에 설정된 버전

      - name: 의존성 패키지 설치
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run flake8 # 코드스타일, 오류 검사
        run: flake8 .

      - name: Run black check # 코드 포매터
        run: black --check .

      - name: Run isort check # import 정렬 도구
        run: isort --check-only .

  # lint-frontend:
  #   name: Frontend Lint
  #   runs-on: ubuntu-latest
  #   working-directory: ./frontend # frontend 서브폴더 지정
  #   steps:
  #     - name: 코드 체크아웃
  #       uses: actions/checkout@v3

  #     - name: Node.js 설정 (버전 지정)
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18

  #     - name: 의존성 설치
  #       run: npm ci

  #     - name: ESLint 실행
  #       run: npm run lint
