# .github/workflows/lint.yml
name: "PR Lint Check"

# PR이 생성되거나 업데이트될 때마다 실행
on:
  pull_request:
    branches: ["answer"]
    types: [opened, synchronize, reopened]

jobs:
  lint-backend:
    name: Backend Lint
    runs-on: ubuntu-latest
    steps:
      - name: GitHub 레포지토리의 코드 체크아웃
        uses: actions/checkout@v3

      - name: Python 설정 (버전 지정)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # 프로젝트에 설정된 버전

      - name: 의존성 패키지 설치
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pylint pylint-django 

      - name: Run pylint check
        run: |
          source venv/bin/activate --load-plugins pylint_django \
           --django-settings-module=seminar.settings \
           --disable=C,R,W \
           --ignore=venv .
           
